#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers {
    _DEFAULT,
    _NUM,
    _SYM,
    _FN,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[_DEFAULT] = LAYOUT_split_3x6_3(KC_TAB, KC_SCLN, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC, KC_ESC, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_SLSH, KC_LSFT, KC_QUOT, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RALT, KC_LGUI, MO(2), KC_SPC, KC_ENT, MO(1), KC_RCTL),
                                                              [_NUM]     = LAYOUT_split_3x6_3(KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RALT, KC_LGUI, MO(3), KC_SPC, KC_ENT, KC_TRNS, KC_RCTL),
                                                              [_SYM]     = LAYOUT_split_3x6_3(KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_UNDS, KC_PIPE, KC_BSPC, KC_ESC, KC_PLUS, KC_LBRC, KC_LCBR, KC_LPRN, KC_BSLS, KC_EQL, KC_RPRN, KC_RCBR, KC_RBRC, KC_MINS, KC_GRV, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RALT, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, MO(3), KC_RCTL),
                                                              [_FN]      = LAYOUT_split_3x6_3(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_MPLY, KC_MSTP, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, KC_TRNS, KC_RCTL)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

#ifdef OLED_ENABLE
const char *read_logo(void);
const char *read_timelog(void);
void        set_keylog(uint16_t keycode, keyrecord_t *record);
const char *read_keylog(void);
const char *read_keylogs(void);

// MOD_MASK_CTRL
// MOD_MASK_SHIFT
// MOD_MASK_ALT
// MOD_MASK_GUI

static void render_layer_block(void) {
    switch (get_highest_layer(layer_state)) {
        case _DEFAULT:
            oled_write_ln_P(PSTR("DVO"), false);
            break;
        case _FN:
            oled_write_ln_P(PSTR("FUN"), false);
            break;
        case _NUM:
            oled_write_ln_P(PSTR("NUM"), false);
            break;
        case _SYM:
            oled_write_ln_P(PSTR("SYM"), false);
            break;
        default:
            oled_write_ln_P(PSTR("Undefined"), false);
    }
    oled_write_ln_P(PSTR(""), false);
}

static void render_mod(uint8_t mod, uint8_t mask, char *name) {
    if (mod & mask) {
        oled_write_ln_P(PSTR(name), false);
    } else {
        oled_write_ln_P(PSTR(""), false);
    }
}

static void render_mod_block(void) {
    uint8_t mod = get_mods() | get_oneshot_mods();
    render_mod(mod, MOD_MASK_CTRL, "CTRL");
    render_mod(mod, MOD_MASK_SHIFT, "SHIFT");
    render_mod(mod, MOD_MASK_ALT, "ALT");
    render_mod(mod, MOD_MASK_GUI, "GUI");
    oled_write_ln_P(PSTR(""), false);
}

static void render_master(void) {
    render_layer_block();
    render_mod_block();
    oled_write_ln(read_keylogs(), false);
    oled_write_ln_P(PSTR(""), false);
    oled_write_ln_P(PSTR(""), false);
}

static void render_logo(void) {
    oled_write(read_logo(), false);
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        render_master();
    } else {
        render_logo();
    }
    return false;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        set_keylog(keycode, record);
    }
    return true;
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (!is_keyboard_master()) return OLED_ROTATION_180; // flips the display 180 degrees if offhand
    return rotation;
}

#endif
